[package]
name = "obsidian_ui_quill"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_mod_stylebuilder = { workspace = true }
quill = { workspace = true }
# bevy_mod_picking = { workspace = true }
